- hosts: all
  vars: 
    msg: | 
        GROUP NAMES Variables ("group_names"):
        --------------------------------
        {{ group_names | to_nice_json }}
 
        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}
 
        HOST Variables ("hostvars"):
        --------------------------------
        service = {{ service }} 
        cluster = {{ cluster }}
        version = {{ version }}
  tasks:
    - debug: 
        msg: "{{ msg.split('\n') }}"
