# https://learn.hashicorp.com/consul/datacenter-deploy/deployment-guide#configure-consul-server-

- template:
    src: server.hcl.j2
    dest: /etc/consul.d/server.hcl
    owner: root
    group: root
    mode: 0644
  become: yes

- systemd:
    name: consul
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
